---
defaults:
  llm_provider: groq
  llm_model: llama3-8b-8192
  llm_temperature: 0.7
  llm_max_tokens: 1024
  hf_embedding_model: BAAI/bge-small-en-v1.5
  news_source: Benzinga
  fundamental_freq: Quarterly
  start_date: "2023-01-01"
  tickerid: NVDA
  tickerids:
    - AMZN
    - AAPL
    - NVDA
    - GOOGL
    - WMT
    - MSFT
    - TSLA
    - JPM
    - BAC
    - WFC
    - XOM
  openai_models:
    - gpt-4o
    - gpt-4o-mini
