---
defaults:
  llm_provider: groq
  llm_providers:
    - groq
    - openai
    - huggingface
  llm_model: llama3-8b-8192
  llm_temperature: 0.7
  llm_max_tokens: 1024
  hf_embedding_model: sentence-transformers/all-MiniLM-L6-v2
  news_source: Benzinga
  fundamental_freq: Quarterly
  start_date: "2023-01-01"
  tickerid: NVDA
  tickerids:
    - AMZN
    - AAPL
    - NVDA
    - GOOGL
    - WMT
    - MSFT
    - TSLA
    - JPM
    - BAC
    - WFC
    - XOM
  openai_models:
    - gpt-4o
    - gpt-4o-mini
  crew: news
  crews:
    - news
    - SEC
  crew_output_dir: finmas_output
  filings_dir: filings
