---
defaults:
  llm_provider: groq
  llm_providers:
    - openai
    - groq
  groq_llm_model: llama3-8b-8192
  openai_llm_model: gpt-4o-mini
  openai_models:
    - gpt-4o-mini
    - gpt-4o
  llm_temperature: 0.0
  llm_max_tokens: 1024
  hf_embedding_model: BAAI/bge-small-en-v1.5
  hf_embedding_models:
    - BAAI/bge-small-en-v1.5
    - sentence-transformers/all-MiniLM-L6-v2
    - sentence-transformers/all-mpnet-base-v2
    - nomic-ai/nomic-embed-text-v1.5
    - BAAI/bge-large-en-v1.5
    - FinLang/investopedia_embedding
  openai_embedding_model: text-embedding-3-small
  openai_embedding_models:
    - text-embedding-3-small
    - text-embedding-3-large
    - text-embedding-ada-002
  similarity_top_k: 3
  news_source: Benzinga
  news_sources:
    - Benzinga
    - Yahoo
  fundamental_freq: Annual
  news_start_date: 2024-10-01
  news_end_date: 2024-11-10
  news_max_num_symbols: 5 # Maximum number of symbols to be used in a news article
  tickerid: NVDA
  tickers_market_cap_exclude:
    - Micro
    - Nano
  only_sp500_tickers: False
  crew: sec_mda_risk_factors
  crews:
    News: news
    SEC: sec
    SEC MD&A and Risk Factors: sec_mda_risk_factors
    Market Data: market_data
    Combined: combined
  crewai:
    max_iterations: 10
    max_requests_per_minute: 30
  embedding_models_dir: embedding_models
  crew_output_dir: output
  crew_logs_dir: logs
  filings_dir: filings
  logs_dir: logs
  data_dir: data
  vector_store_index_dir: vector_store_index
  fundamentals_dir: data/fundamentals
  sec_filing_key_metrics_for_compression:
    - Total revenue
    - Net income
    - Operating expenses
    - Risk factors
    - Cash flow
    - Management's discussion
  sec_filing_types_selected:
    - 10-K
  sec_filing_types:
    - 10-Q
    - 10-K
  sec_filing_sections:
    - mda
    - risk_factors
  llm_model_cost:
    gpt-4o-mini:
      input_cost: 1.5e-7
      output_cost: 6.0e-7
    gpt-4o:
      input_cost: 0.000005
      output_cost: 0.000015
  embedding_model_cost:
    text-embedding-3-small: 2.0e-8
    text-embedding-3-large: 1.3e-7
    text-embedding-ada-002: 1.0e-7
  fundamentals_tool:
    include_qoq: False
  include_fundamental_data: True
  include_news: False
  save_fundamental_data: True
  save_news_data: True
  save_text_content: True # Save text content of filings or news
  text_content_dir: output/text_content
