---
defaults:
  llm_provider: groq
  llm_providers:
    - groq
    - openai
    - huggingface
  groq_llm_model: llama3-8b-8192
  openai_llm_model: gpt-4o-mini
  openai_models:
    - gpt-4o-mini
    - gpt-4o
  llm_temperature: 0.0
  llm_max_tokens: 1024
  hf_embedding_model_news: BAAI/bge-small-en-v1.5
  hf_embedding_model_sec: sentence-transformers/all-MiniLM-L6-v2
  hf_embedding_models:
    - BAAI/bge-small-en-v1.5
    - sentence-transformers/all-MiniLM-L6-v2
    - sentence-transformers/all-mpnet-base-v2
    - nomic-ai/nomic-embed-text-v1.5
    - BAAI/bge-large-en-v1.5
    - FinLang/investopedia_embedding
  openai_embedding_model_news: text-embedding-3-small
  openai_embedding_model_sec: text-embedding-3-small
  openai_embedding_models:
    - text-embedding-3-small
    - text-embedding-3-large
    - text-embedding-ada-002
  similarity_top_k: 3
  news_source: Benzinga
  news_sources:
    - Benzinga
    - Yahoo
  fundamental_freq: Annual
  start_date: "2023-01-01"
  tickerid: NVDA
  tickers_market_cap_exclude:
    - Micro
    - Nano
  only_sp500_tickers: False
  crew: news
  crews:
    - news
    - sec
    - sec_mda_risk_factors
  embedding_models_dir: embedding_models
  crew_output_dir: output
  filings_dir: filings
  logs_dir: logs
  sec_filing_index_dir: sec_filing_index
  sec_filing_key_metrics_for_compression:
    - Total revenue
    - Net income
    - Operating expenses
    - Risk factors
    - Cash flow
    - Management's discussion
  sec_filing_types_selected:
    - 10-K
  sec_filing_types:
    - 10-Q
    - 10-K
  sec_filing_sections:
    - mda
    - risk_factors
