site_name: FinMAS - Financial Analysis Multi-agent System
site_url: https://KevorkSulahian.github.io/agentic-llm-for-better-results
docs_dir: docs
repo_name: agentic-llm-for-better-results
repo_url: https://github.com/KevorkSulahian/agentic-llm-for-better-results

nav:
  - Home: index.md
  - Tutorial:
      - tutorial/index.md
      - News Analysis: tutorial/news.md
  - Settings: settings.md
  - Components:
      - components/index.md
      - Crews: components/crews.md
      - Data: components/data.md
      - Packages: components/packages.md
      - LLM Models: components/llm_models.md
      - Embedding Models: components/embedding_models.md
  - Development: development.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest

markdown_extensions:
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search
  - macros:
      include_dir: docs/include
  - mermaid2
