site_name: FinMAS - Financial Analysis Multi-agent System
site_url: https://KevorkSulahian.github.io/agentic-llm-for-better-results
docs_dir: docs/
repo_url: https://github.com/KevorkSulahian/agentic-llm-for-better-results
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Tutorial:
      - tutorial/index.md
      - News Analysis: tutorial/news.md
  - Configuration: configuration.md
  - Components:
      - components/index.md
      - Crews: components/crews.md
      - Packages: components/packages.md
      - LLM Models: components/llm_models.md
      - Embedding Models: components/embedding_models.md
  - Data:
      - data/index.md
      - SEC Filings:
          - data/sec/index.md
          - Parsing: data/sec/parsing.md
      - News: data/news.md
      - Fundamentals: data/fundamentals.md
  - Development: development.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest
    - content.action.edit
    - content.action.view

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css

markdown_extensions:
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - toc:
      permalink: true

plugins:
  - search
  - macros:
      include_dir: docs/include
  - mermaid2
